-- Day-wise IoT running data (unified from multiple vendor upload formats).
-- Safe to re-run: uses IF NOT EXISTS / DROP POLICY IF EXISTS

create table if not exists public.iot_data (
  id bigint generated by default as identity primary key,
  vehicle_number text,
  run_date date not null,
  total_distance numeric,
  data_source text not null,
  raw_vehicle_id text,
  vehicle_master_id bigint references public.vehicle_master (id),
  lookup_matched boolean not null default false,
  lookup_match_type text,
  created_at timestamptz not null default now()
);

create index if not exists iot_data_run_date_idx on public.iot_data (run_date desc);
create index if not exists iot_data_vehicle_number_idx on public.iot_data (vehicle_number);
create index if not exists iot_data_data_source_idx on public.iot_data (data_source);
create unique index if not exists iot_data_unique_row
  on public.iot_data (data_source, run_date, coalesce(vehicle_number, ''), coalesce(raw_vehicle_id, ''));

alter table public.iot_data enable row level security;

drop policy if exists "Allow anon read iot_data" on public.iot_data;
create policy "Allow anon read iot_data"
  on public.iot_data for select to anon using (true);

drop policy if exists "Allow anon insert iot_data" on public.iot_data;
create policy "Allow anon insert iot_data"
  on public.iot_data for insert to anon with check (true);

drop policy if exists "Allow anon delete iot_data" on public.iot_data;
create policy "Allow anon delete iot_data"
  on public.iot_data for delete to anon using (true);
