-- Day-wise IoT running data (unified from multiple vendor upload formats).
-- Safe to re-run; existing rows are preserved.
-- After this file, run sql/fix_upload_integrity.sql to enable the upload RPC,
-- then sql/fix_dashboard_last_upload_timeout.sql for the dashboard RPC.

create table if not exists public.iot_data (
  id bigint generated by default as identity primary key,
  vehicle_number text,
  run_date date not null,
  total_distance numeric,
  data_source text not null,
  raw_vehicle_id text,
  vehicle_master_id bigint references public.vehicle_master (id),
  lookup_matched boolean not null default false,
  lookup_match_type text,
  upload_batch_id text,
  created_at timestamptz not null default now()
);

create index if not exists iot_data_run_date_idx on public.iot_data (run_date desc);
create index if not exists iot_data_vehicle_number_idx on public.iot_data (vehicle_number);
create index if not exists iot_data_data_source_idx on public.iot_data (data_source);
-- A nonunique index preserves legacy duplicate rows. The upload RPC enforces
-- source/date/normalized-vehicle uniqueness for all future client uploads.
create index if not exists iot_data_normalized_vehicle_date_idx
  on public.iot_data (
    data_source,
    run_date,
    (regexp_replace(upper(coalesce(nullif(btrim(vehicle_number), ''), raw_vehicle_id, '')), '[^A-Z0-9]', '', 'g'))
  );

alter table public.iot_data enable row level security;

drop policy if exists "Allow anon read iot_data" on public.iot_data;
create policy "Allow anon read iot_data"
  on public.iot_data for select to anon, authenticated using (true);

drop policy if exists "Allow anon insert iot_data" on public.iot_data;
drop policy if exists "Allow anon delete iot_data" on public.iot_data;

-- Client writes go only through save_iot_upload; no anonymous deletion.
revoke all privileges on table public.iot_data from public, anon, authenticated;
grant select on table public.iot_data to anon, authenticated;
